### ISSUE TITLE
Please simplify APCSP Students section of README

### ISSUE THREAD

**Issue by jelkner** [ModdedGamers/brew-easy-install#1]
You have **APCSP Students - 1st/2nd Quarter**, and **APCSP Students - 4th Quarter** in the ``README`` file.  This is confusing for the 9th graders reading this section, and not needed.  We don't use node anymore.  Could you please combine the two section into one **APCSP Students** section that only has Python installation info.  Thanks!

**Comment by pyrox0** [comment]
Updated!
